:icons: fonts

= Instrukcje obsługi SpotBugs

SpotBugs :: następca FindBugs, który zatrzymał się na JDK7. Bazuje na koncepcie "wzorców błędów".

Działamy na wtyczce do Mavena: https://spotbugs.github.io/spotbugs-maven-plugin/


== Z Maven Central

[source, xml]
.wpinamy w reporting > plugins
      <plugin>
        <groupId>com.github.spotbugs</groupId>
        <artifactId>spotbugs-maven-plugin</artifactId>
        <version>3.1.12.3-SNAPSHOT</version>
      </plugin>

Zauważcie nietypową wersję - wzięta z dokumentacji wtyki.

== Pomoc?

TIP: `git checkout start`

Niegłupie byłoby odpalić polecenia z `TODO Złej klasy`. I poczytać.

=== PMD dla Mavena

. `pmd:pmd` - tworzy raport w kilku formatach
. `pmd:cpd` - j.w. dla narzędzia Copy-Paste Detector
. `pmd:check` - domyślnie przy `pmd`
. `cpd:check` - j.w. przy `cpd`

== Demo PMD

. wpięcie do POMa
. `mvn pmd:pmd`, per `ZłaKlasa`

== Wpinanie w budowę

TIP: `git checkout pmd-budowa`

. Z automatu nie mamy PMD. Trzeba je wpiąć.
. Powyższe wpina i pozwala nam z niego skorzystać - ale ręcznie.
. By PMD startowało przy każdej budowie...

[source, xml]
.pełna konfiguracja do wpięcia w build > plugins
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-pmd-plugin</artifactId>
                <version>${version.plugin.maven.pmd}</version>
                <executions>
                    <execution>
                        <phase>verify</phase>
                        <goals>
                            <goal>check</goal>
                            <goal>cpd-check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
