:icons: fonts

= Instalacja i obsługa PMD

PMD :: Please, Don't shoot the Messenger, program do statycznej analizy kodu

Wtyka PMD :: Mavenowa wtyczka, używająca PMD

Czyli np., wtyczka 3.9, używa PMD 6.0.

Najnowsze PMD to 6.20, tak przy okazji.

== Z Maven Central

[source, xml]
.by mieć PMD w build > plugins > plugin piszemy
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-pmd-plugin</artifactId>
                <version>${version.plugin.maven.pmd}</version>

Polecam też w `<properties>` wersję ustawić na `3.9.0`.

== Pomoc?

TIP: `git checkout start`

Niegłupie byłoby odpalić polecenia z `TODO Złej klasy`. I poczytać.

=== PMD dla Mavena

. `pmd:pmd` - tworzy raport w kilku formatach
. `pmd:cpd` - j.w. dla narzędzia Copy-Paste Detector
. `pmd:check` - domyślnie przy `pmd`
. `cpd:check` - j.w. przy `cpd`

== Demo PMD

. wpięcie do POMa
. `mvn pmd:pmd`, per `ZłaKlasa`

== Wpinanie w budowę

TIP: `git checkout pmd-budowa`

. Z automatu nie mamy PMD. Trzeba je wpiąć.
. Powyższe wpina i pozwala nam z niego skorzystać - ale ręcznie.
. By PMD startowało przy każdej budowie...

[source, xml]
.pełna konfiguracja do wpięcia w build > plugins
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-pmd-plugin</artifactId>
                <version>${version.plugin.maven.pmd}</version>
                <executions>
                    <execution>
                        <phase>verify</phase>
                        <goals>
                            <goal>check</goal>
                            <goal>cpd-check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

== Drugie demo PMD

. wpięcie do POMa
. zmiana faz
. `mvn pmd:pmd`, per `ZłaKlasa`

Za: https://maven.apache.org/plugins/maven-pmd-plugin/examples/violationChecking.html

== Trzecie demo PMD

. wpięcie do POMa
. zmiana faz
. `mvn pmd:pmd`, per `ZłaKlasa`
. *jaka jest różnica?*

== Czwarte demo PMD

. wpięcie do POMa
. zmiana faz
. `mvn pmd:pmd`, per `ZłaKlasa`
. raport

[[NOTE]]
.Problem z Xrefem
____
Jeśli w konsoli leci:
`[WARNING] Unable to locate Source XRef to link to - DISABLED`

to:
<linkXref>false</linkXref>
w konfiguracji (sekcja build, nie reporting!) - ponoć we własnościach projektu też się da

[source,xml]
.dodajmy jxr do skakania po źródach w raportach
<reporting>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-jxr-plugin</artifactId>
            <version>2.3</version>
        </plugin>
    </plugins>
</reporting>

JXR to wtyka umożliwiająca przegląd kodu w raportach Mavena.
Daje też możliwość skoku do źródeł tamże (PMD zgłasza problem w linii 4 pliku Coś.java, linia jest linkiem).

*Czemu ktoś miałby z tego rezygnować?*

. Może wydłużać czas budowy.
. Jenkinsowe narzędzia potrafią to obsłużyć same z siebie, bez JXRa.
____

=== Ćwiczenie

. wygenerujmy raport PMD gdzie można skakać do źródeł
. usuńmy łącza i wtykę JXR ale straćmy też ostrzeżenie

=== Konfiguracja PMD

Za: https://maven.apache.org/plugins/maven-pmd-plugin/check-mojo.html

Albo przez Intellij: wejdź do POMa i

. sekcja reporting, wtyka PMD, znacznik `<configuration>`
. _Ctrl_+_Space_

=== Pusty raport i co dalej

. brawo! tak ma być.
.. chyba, że nie powinno.
.. jak niepusty, to jest się czym martwić.
. dodajmy regułę
. pozmieniajmy zestawy reguł
. dodajmy własny zestaw reguł

== Reguły

PMD regułami stoi.

. zerknijmy na `target/maven-pmd-plugin-default.xml`
. wersja w Gicie Mavena: https://gitbox.apache.org/repos/asf?p=maven-pmd-plugin.git;a=blob_plain;f=src/main/resources/rulesets/java/maven-pmd-plugin-default.xml;hb=HEAD
. wtyka zaciąga własne PMD, które
.. rozpoznaje te reguły jakie zna
.. i tak pogrupowane jak ma

TIP: możesz się dowiedzieć "nie znam takiej reguły", bo w dokumentacji patrzysz na nowszą wersję PMD (lub podajesz zestaw który zmienił nazwę lub ścieżkę)! https://stackoverflow.com/questions/27571148/adding-a-ruleset-to-pmd[Przykład]

=== Reguła?

. klasa Jawowa
. plik XML
. nie dziś raczej

TIP: https://www.i-love-software-engineering.de/writing-your-own-custom-pmd-rules-pmd-eclipse-maven/[dobra lektura w temacie]

Zwykle ludzie zaczynają od zabawy zestawami już istniejącymi

=== Ćwiczenie

Niech Twoje PMD wykorzysta zestawy:
[source,xml]
                       <ruleset>rulesets/java/braces.xml</ruleset>
                       <ruleset>rulesets/java/naming.xml</ruleset>

CAUTION: ostrzeżenia o przestarzałych regułach nie są niczym strasznym po prostu przeczytać i podmienić

=== PMD własny zestaw reguł

[source, XML]
.rodzaje zestawów reguł (po źródle) jakie można wpinać
<configuration>
      <rulesets>
        <!-- wbudowane -->
        <ruleset>/category/java/bestpractices.xml</ruleset>
        <!-- lokalne -->
        <ruleset>/home/USER/PMD/rulesets/strings.xml</ruleset>
        <!-- via URL -->
        <ruleset>http://localhost/design.xml</ruleset>
      </rulesets>
</configuration>

=== Ćwiczenie: weźmy cudzy zestaw!

https://github.com/leanstacks/spring-boot-fundamentals/blob/master/etc/pmd/ruleset.xml

i wykorzystajmy go u nas

=== Ćwiczenie: modernizacja zestawu

pozbądźmy się ostrzeżeń z zestawu leanstack

=== Ćwiczenie: dodanie reguł bezpieczeństwa

do zmodernizowanego zestawu powyżej, dodajmy reguły stąd:

https://pmd.github.io/pmd-6.13.0/pmd_rules_java_security.html

sprawdźmy, że one działają na nowym kodzie!

=== PMD i Owasp 2010

https://github.com/GDSSecurity/GDS-PMD-Security-Rules
